/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "PwmDriver.h"
#include "BasicTimer.h"
#include "GPIOxDriver.h"

GPIO_Handler_t handlerPwmT2C2 = {0};
BasicTimer_Handler_t timerServo = {0};
PWM_Handler_t pwmServo = {0};

void initSys(void);



int main(void)
{
	initSys();

	return 0;
}

void initSys(void){
//	timerServo.ptrTIMx		= TIM2;
//	timerServo.TIMx_Config.TIMx_interruptEnable = 1;
//	timerServo.TIMx_Config.TIMx_mode = BTIMER_MODE_UP;
//
//	BasicTimer_Config(&timerServo);
//	startTimer(&timerServo);

	handlerPwmT2C2.pGPIOx = GPIOA;
	handlerPwmT2C2.GPIO_PinConfig.GPIO_PinNumber = PIN_1;
	handlerPwmT2C2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OSPEED_HIGH;
	handlerPwmT2C2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	handlerPwmT2C2.GPIO_PinConfig.GPIO_PinAltFunMode = AF1;

	GPIO_Config(&handlerPwmT2C2);

	pwmServo.ptrTIMx = TIM2;
	pwmServo.config.channel = PWM_CHANNEL_2;
	pwmServo.config.duttyCicle = 50;
	pwmServo.config.prescaler = 236 ;
	pwmServo.config.periodo = 100;

	pwm_Config(&pwmServo);
	startPwmSignal(&pwmServo);
}


